version: "3"

services:
  mininet:
    image: opennetworking/mn-stratum
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./tmp/mn-stratum:/tmp
      - ./mininet:/mininet
    ports:
      - "50001-50030:50001-50030"
    entrypoint: "/mininet/topo.py --mac --topo trellis"
  onos:
    image: onosproject/onos:2.1.0
    hostname: onos
    container_name: onos
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
#    volumes:
#      - ./tmp/onos:/root/onos/apache-karaf-4.2.6/data/tmp
    environment:
      - ONOS_APPS=gui,drivers.bmv2,pipelines.fabric,segmentrouting,lldpprovider,hostprovider
    links:
      - mininet
